BEGIN TRANSACTION;

DROP TABLE IF EXISTS reviews;
DROP SEQUENCE IF EXISTS seq_review_id;
DROP TABLE IF EXISTS beers;
DROP SEQUENCE IF EXISTS seq_beer_id;
DROP TABLE IF EXISTS brewers;
DROP TABLE IF EXISTS breweries;
DROP SEQUENCE IF EXISTS seq_brewery_id;
DROP TABLE IF EXISTS users;
DROP SEQUENCE IF EXISTS seq_user_id;

CREATE SEQUENCE seq_user_id
  INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;
CREATE TABLE users (
	user_id int DEFAULT nextval('seq_user_id'::regclass) NOT NULL,
	username varchar(50) UNIQUE NOT NULL,
	password_hash varchar(200) NOT NULL,
	zipcode varchar(10),
	email varchar(100),
	role varchar(50) NOT NULL,
	CONSTRAINT PK_user PRIMARY KEY (user_id)
);


INSERT INTO users (username,password_hash, zipcode, email, role) 
VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', '55555', 'example@email.com','ROLE_USER');

INSERT INTO users (username,password_hash, zipcode, email, role) 
VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', '55555', 'example@email.com','ROLE_ADMIN');

INSERT INTO users (username, password_hash, zipcode, email, role) 
VALUES ('Zach','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 
		'45236', 'zach@email.com', 'ROLE_USER');
		
insert into users(username, password_hash, role)
values ('brewer', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'ROLE_BREWER');

CREATE SEQUENCE seq_brewery_id
 INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;
CREATE TABLE breweries (
	brewery_id int DEFAULT nextval('seq_brewery_id'::regclass) NOT NULL,
	brewery_name varchar(50) UNIQUE NOT NULL,
	brewery_location varchar(60) NOT NULL,
	phone_number varchar(20) NOT NULL,
	hours_of_operation varchar(1000) NOT NULL,
	address varchar(300) NOT NULL,
	bio varchar(100000) NOT NULL,
	brewery_img varchar(10000) NOT NULL,
	active boolean NOT NULL,
	CONSTRAINT PK_brewery PRIMARY KEY (brewery_id)
);


INSERT INTO breweries (brewery_name, brewery_location, phone_number,hours_of_operation, address, bio, active, brewery_img)
VALUES ('MadTree', 'Cincinnati, OH', '513-836-8733', 'Thursday: 11AM–11PM; Friday: 11AM–12AM; Saturday: 10AM–12AM; Sunday: 10AM–11PM; Monday: 11AM–11PM; Tuesday: 11AM–11PM; Wednesday: 11AM–11PM', '3301 Madison Road Cincinnati, OH 45209',
'MadTree puts purpose in every pour. Founded in 2013, MadTree has always been driven to craft great beer - but more importantly - to build something bigger than themselves and the high-quality beer they produce. Since the beginning, MadTree has cared deeply about creating meaningful connections with their communities. They embrace their namesake and work to celebrate and protect nature while reducing their impact on the environment. They are proud members of 1% for the Planet, with a commitment to donate 1% of sales to non-profits focused on environmental sustainability. The craftspeople at MadTree wake up every day to connect people to nature and each other. MadTree. Inspiring Madness. Rooted in Purpose', 
true, 'https://cincinnatiusa.com/sites/default/files/styles/Array/public/Venues/MadTree-00.jpg'),
('Great Lakes', 'Cleveland, OH', '216-771-4404', 'Friday: 12–11PM; Saturday: 11:30AM–11PM; Sunday: Closed; Monday: 12–10PM; Tuesday: 12–10PM; Wednesday: 12–10PM; Thursday: 12–10PM', '2516 Market Ave, Cleveland, OH 44113', 
'From the beginning, we have aspired to craft our beloved and award-winning beers in a socially and environmentally responsible way. As we continue to grow and expand, we will do so with care and respect for our products, employees, customers, and planet. Our employees are our most valued asset, so we have brewed a careful selection process to hire only the best ambassadors for our company. We seek driven, enthusiastic people who share a dedication to our core values: passion for product, respect for resources, the fostering of relationships, and the sharing of success. We continuously strive to grow our innovative and resourceful team of individuals with high standards, integrity, and vision—and who can also appreciate sharing a little camaraderie or a pint with their co-workers. ', 
true, 'https://d1ynl4hb5mx7r8.cloudfront.net/wp-content/uploads/2020/02/17140001/great-lakes-1024x633.jpg'),
('50 West', 'Cincinnati, OH', '513-834-8789', 'Friday: 11AM–11PM; Saturday: 11AM–11PM; Sunday: 11AM–9PM; Monday: 11AM–10PM; Tuesday: 11AM–10PM; Wednesday: 11AM–10PM; Thursday: 11AM–10PM', '7605 Wooster Pike, Cincinnati, OH 45227', 
'Located in a former roadside speakeasy on US Route 50 heading west into the city of Cincinnati, Fifty West Brewing Company first opened its doors in November of 2012. Stretching across the country, U.S.Route 50 passes through 12 states from Ocean City, Maryland to Sacramento, California. It’s our pleasure at the Fifty West to serve you tastes of Americana from this fabled road trip. We thrive to provide each customer an experience as fond and memorable as a long haul across the country with your co-pilot riding shotgun. At Fifty West, every beer is a journey. Join us for the ride.', 
true, 'https://media1.citybeat.com/citybeat/imager/u/original/12086253/copy_of_20180412_4e9a2481.5c9e70e104fc3.png'),
('Fretboard', 'Cincinnati, OH', '513-914-4677', 'Friday: 12PM–12AM; Saturday: 12PM–12AM; Sunday: 12–8PM; Monday: 3–10PM; Tuesday: 3–10PM; Wednesday: 3–10PM; Thursday: 3–10PM', '5800 Creek Rd, Cincinnati, OH 45242', 
		'Fretboard Brewing Company is an award-winning brewery & live music venue in Blue Ash, OH. #brewsintune.', true, 'https://www.gannett-cdn.com/presto/2021/11/03/PCIN/49bf6db3-ff37-4b74-b615-fab35b87d110-Fretboard.jpg'),
		('High Grain', 'Cincinnati, OH', '513-791-7000', 'Monday: 3PM-10PM; Tuesday: 3PM-10PM; Wednesday: 3PM-10PM; Thursday: 3PM–10PM; Friday: 12PM–11PM; Saturday: 11AM–11PM; Sunday: 11PM–8PM', 
		'6860 Plainfield Road, Cincinnati, OH, 45236', 'We’re a brewery with a scratch kitchen making sustainable choices from the onset of each project. We love beer and believe beer is best with a good meal with locally sourced food. Our seasonally rotating menu includes vegan options and local foods from Cincy farms such as Gorman Heritage Farm and Perch Farms.', true, 'https://media.bizj.us/view/img/11339109/highgrain29*1200xx1800-1013-0-94.jpg'),
		('Nine Giant', 'Cincinnati, OH', '513-366-4550', 
'Monday: CLOSED; Tuesday: 11:30AM–10PM; Wednesday: 11:30AM–10PM; Thursday: 11:30PM–10PM; Friday: 11:30PM–10PM; Saturday: 11:30AM–11PM; Sunday: 11:30PM–9PM', '6095 Montgomery Rd, Cincinnati, OH 45213', 
'Our crack team of beer wizards crafts award-winning small batch beers to delight any tummy. Our beers change frequently so there’s always something new and delicious to indulge in.', true, 'https://www.gannett-cdn.com/media/2016/06/23/Cincinnati/Cincinnati/636022930752296332-062316-NINE-GIANT-335.jpg?width=640'),
('Rhinegeist', 'Cincinnati, OH', '513-381-1367', 
'Monday: 3PM-10PM; Tuesday: 3PM-10PM; Wednesday: 3PM-10PM; Thursday: 3PM-10PM; Friday: 12PM–12AM; Saturday: 12PM–12AM; Sunday: 12PM–9PM', 
'1910 Elm St, Cincinnati, OH 45202', 'Rhinegeist is located in the historic Over-the-Rhine neighborhood in Cincinnati, Ohio. Our 25,000 square foot, active brewing facility is housed in the former bottling plant of Christian Moerlein Brewing Co., a formidable pre-Prohibition beermaker. We cant wait to meet ya!', true, 'https://media-exp1.licdn.com/dms/image/C4E1BAQGCkrtCNsSMMg/company-background_10000/0/1578514862862?e=2147483647&v=beta&t=Tbeps4MHeNRqWXULVPPqvyG_fYdFIBf3bT3_twwQgXg'),
('Braxton', 'Covington, KY', '859-261-5600', 
'Monday: 3PM-9PM; Tuesday: 11AM-10PM; Wednesday: 11AM-10PM; Thursday: 11AM-10PM; Friday: 11AM-12AM; Saturday: 11AM-12AM; Sunday: 11AM–9PM', 
 '27 West 7th Street, Covington, KY 41011', 'Welcome to Braxton Brewing Company. You’re witnessing a dream coming to life. A place where ideas are born and fermented. It’s a great deal of work, but hell, that’s what makes a dream worth pursuing. This brewery celebrates determination, knowledge, and the humble pride we wave like a battle flag.', true, 'https://www.americanway.com/public/uploads/Cincinnati-Braxton-Brewing-Co-courtesy.jpg'),
 ('Cartridge', 'Maineville, OH', '513-697-3434', 
'Monday: CLOSED; Tuesday: 4PM-10PM; Wednesday: 4PM-10PM; Thursday: 4PM-10PM; Friday: 11AM-11PM; Saturday: 11AM-11PM; Sunday: 11AM–9PM', 
'1411 Grandin Rd, Maineville, OH 45039', 'Opened in 1916, the historic Peters Cartridge Factory was once a community hub and the heart of Kings Mills. The space is now fully restored and is home to Cartridge Brewing. Built on the banks of the Little Miami River, Cartridge Brewing is a veteran-owned business focused on celebrating the traditional craft of brewing. Cartridge is proud to serve a selection of old world beers alongside easy-drinking specialty styles – all brewed on-site in our 15 bbl brewhouse.', true, 'https://cartridgebrewing.com/assets/general/_1200x630_crop_center-center_82_none/CTG_Hero.jpg?mtime=1531776428'),
('Sonder', 'Mason, OH', '513-779-2739', 
'Monday: 11AM-10PM; Tuesday: 11AM-10PM; Wednesday: 11AM-10PM; Thursday: 11AM-10PM; Friday: 11AM-12AM; Saturday: 11AM-12AM; Sunday: 10AM–9PM',  
'8584 Duke Blvd, Mason, OH 45040', 'Just like every person has a unique story, so does every beer. The story of Sonder beer begins with our unique, high-quality beer selection brewed on site at the Sonder Brewing production facility and taproom located in the Cincinnati area at 8584 Duke Boulevard in Mason, Ohio. The 15,200-square-foot building holds a 30-barrel brew house with American-made equipment and features 2,000-square-feet of taproom space. The Sonder brewing team, led by Chase Legler, has over 20 years of craft brewing experience, with a passion for quality and flavor that showcases throughout the Sonder beer lineup.', true, 'https://images.squarespace-cdn.com/content/v1/58c814d2414fb5205e266a1c/1573761869001-9UZJOYSOWTIT0S32URDZ/Beer+Garden+Sunet.jpg?format=1000w'),
('Fake Brewery 3', 'City, State', '555-555-5555', 'Thursday: 11AM–11PM, Friday: 11AM–12AM, Saturday: 10AM–12AM, Sunday: 10AM–11PM,
Monday: 11AM–11PM, Tuesday: 11AM–11PM, Wednesday: 11AM–11PM', '1010 Street Address, City, State 01010', 'They make beers', false, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chandler-San_Tan_Brewery-2007.jpg/1200px-Chandler-San_Tan_Brewery-2007.jpg'),
('Fake Brewery 4', 'City, State', '555-555-5555', 'Thursday: 11AM–11PM, Friday: 11AM–12AM, Saturday: 10AM–12AM, Sunday: 10AM–11PM,
Monday: 11AM–11PM, Tuesday: 11AM–11PM, Wednesday: 11AM–11PM', '1010 Street Address, City, State 01010', 'They make beers', false, 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Chandler-San_Tan_Brewery-2007.jpg/1200px-Chandler-San_Tan_Brewery-2007.jpg');

CREATE TABLE brewers (
	brewer_id int CONSTRAINT fk_users REFERENCES users(user_id),
	brewery_id int CONSTRAINT fk_breweries REFERENCES breweries(brewery_id)
);


INSERT INTO brewers (brewer_id, brewery_id)
VALUES ((SELECT user_id
		FROM users 
		WHERE username= 'brewer'),
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name ='MadTree'));
	   
VALUES ((SELECT user_id
		FROM users 
		WHERE username= 'brewer'),
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name ='Great Lakes Brewery'));

CREATE SEQUENCE seq_beer_id
 INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;
CREATE TABLE beers(
	beer_id int DEFAULT nextval('seq_beer_id'::regclass) NOT NULL,
	beer_name varchar(50) NOT NULL,
	abv decimal NOT NULL,
	beer_type varchar(50) NOT NULL,
	ibu int NOT NULL,
	hops varchar(100) NOT NULL,
	description varchar(50000) NOT NULL,
	beer_img varchar(1000),
	malts varchar(100),
	available boolean,
	brewery_id int CONSTRAINT fk_breweries REFERENCES breweries(brewery_id),
	CONSTRAINT PK_beer PRIMARY KEY (beer_id)
);


INSERT INTO beers(beer_name, abv, beer_type, brewery_id, ibu, hops, description, available, beer_img)
VALUES ('42 Mile', 5.6, 'Cider', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 0.0, '', 'A semi-sweet cider brewed with apples grown locally at Beiersdorfer Orchard.', true, 'https://untappd.akamaized.net/photos/2021_10_24/c9088acfac56d856fa18a955247bd770_640x640.jpg'),		('Bockaveli', 7.6, 'Bock', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 18.0, '', 'Single / Traditional', true, 'https://untappd.akamaized.net/photos/2022_04_15/688fff70a4f25671639c141d911fb943_raw.jpg'),
		('Born To Be Mild', 3.5, 'Mild',
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 22.0, '', 'Bready, toasty malt with noticeable but not overpowering black tea notes.', true, 'https://untappd.akamaized.net/photos/2022_02_27/47add1842f940a5d2ae2ca780c4eb2eb_640x640.jpg'),
	   ('Burning Apparition', 6.66, 'Peanut Butter Porter', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 0.0, 'N/A', 'Peanut Butter Porter', true, 'https://untappd.akamaized.net/photos/2022_03_18/32ec0528e92a4417d64fc2a1057b9d58_640x640.jpg'),
		('Espressoself', 4.9, 'Brown Ale', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 17.0, '', 'Light bodied brown ale brewed with Deeper Roots coffee. Espresso coffee knows chocolate and Caramel note clean and let a dry finish.', true, 'https://untappd.akamaized.net/photos/2022_03_24/306c9af049188407f4ed01447bba4b68_640x640.jpg'),
		('Fable', 7.0, 'Porter', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 30.0, '', 'Baltic', true, 'https://untappd.akamaized.net/photos/2022_04_06/ccc8278d572052689b74ca3933b50070_raw.jpg'),
		('Fiesta Forever', 4.6, 'Fruit Tart Ale', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 18.0, '', 'A margarita version of Shade with a boost of lime juice and sea salt.', true, 'https://untappd.akamaized.net/photos/2021_07_06/bf20e6d1e208e0d8d0dc6499e1d70a21_640x640.jpg'),
		('Galaxy High', 9.5, 'IPA', 
		(SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 120.0, '', 
	   'Join two Australian hops as you encounter a crazy collection of tropical and dank flavors throughout this Imperial IPA. It’s big on your palate… disruptive even. Think "trophic cascades" disruptive.', true, 
	   'https://cdn2.cincinnatimagazine.com/wp-content/uploads/sites/5/2015/03/Galaxy-High-01-e1426528515292.jpg'),
		('Happy Amber', 6.0, 'Red Ale', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 30.0, '', 
	   '2018 GABF Gold Medal Winner | This dry-hopped ale combines caramel and biscuit malt flavors in happy equilibrium with late addition American hops. The approachable balance is intentional although the name is a “hoppy” accident.', true, 
	   'https://pbs.twimg.com/media/FNl84_yXIAY0-gF?format=jpg&name=large'),
		('Its October Somewhere', 5.7, 'Lager - Amber', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 17.0, '', '', true, 'https://untappd.akamaized.net/photos/2022_04_13/e612bf38977213957c572ab70343de0a_640x640.jpg'),
		('Legendary Lager', 4.2, 'Lager', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'MadTree'), 15.0, '', '', true, 'https://www.gannett-cdn.com/presto/2021/03/08/PCIN/a8100e77-63ef-4c46-9887-ab30532d35c6-20210301_191851.jpg'),
	('Straight Out Of Belgium', 
	9.9, 
	'Belgian Tripel', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'MadTree'), 
	0.0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_03/9c582475b48a460839e3f5eea05c30ed_640x640.jpg'),
	('Summer Camp Haze', 
	7.0, 
	'IPA - New England / Hazy', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'MadTree'), 
	30.0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_16/81d0cd0e131b66327ad1355f9f72a1fd_640x640.jpg'),
	('Treesearch No. 9', 
	6.5, 
	'IPA - American', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'MadTree'), 
	0.0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_14/45146ba5401490b12f6c39411c0bc80e_640x640.jpg'),
	('Tropical Psychopathy', 
	6.9, 
	'IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'MadTree'), 
	69.0, 
	'', 
	'IPA with passionfruit, orange, and guava', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_15/53747441aa80fb8a597d31273218b4cf_640x640.jpg'),
	('Turbulence', 
	5.0, 
	'Blonde Stout', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'MadTree'), 
	36.0, 
	'', 
	'Tropical Blonde Stout w/ lactose, citrus, coconut, coffee and cocoa nibs', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_20/1952815f14780a332847ede2730057e1_640x640.jpg'),
	('Dortmunder Gold', 
	5.8, 
	'Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	30, 
	'Cascade, Mt. Hood', 
	'A classic award-winning balance of sweet malt and dry hop flavors, proudly waving the flag for Cleveland and refreshing beer drinkers everywhere since 1988.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/dortmunder_cleveland_sign.jpeg?itok=xvFohrwo'),
	('Eliot Ness', 
	6.1, 
	'Amber Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	27, 
	'Mt. Hood', 
	'Admittedly, it’s a bit of a paradox to name our Amber Lager for history’s most famous agent of prohibition. But it’s a smooth, malty (and dare we say, arresting?) paradox.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/eliot_ness_brewpub.jpeg?itok=ZB4EFgmo'),
	('Great Lakes', 
	6.5, 
	'IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	50, 
	'Lemondrop, Simcoe, Mosaic Cryo Hops, Azacca', 
	'With a breezy, aromatic hop blend and clean malt flavor, our lightly filtered American IPA is as bright, bracing, and inviting as the beautiful lakes we call home. ', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/great_lakes_ipa_forest.jpeg?itok=gt-nAH8Q'),
	('Burning River', 
	6.0, 
	'Pale Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	45, 
	'Cascade, Centennial', 
	'Greetings from Cleveland! Where an infamous river fire rekindled appreciation for our region’s natural resources (like the malt and hops illuminating this Pale Ale).', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/burning_river_fire.jpeg?itok=NI5h7ci7'),
	('Commodore Perry', 
	7.7, 
	'IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	70, 
	'Simcoe, Williamette, Cascade', 
	'What’s this? A British-style IPA named after the man who defeated His Majesty’s Royal Navy in the War of 1812? Consider this a bold, hoppy (and mildly ironic) plunder of war.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/00100lrportrait_00100_burst20210121143510516_cover.jpg?itok=1-aRBpXd'),
	('Edmund Fitzgerald', 
	6.0, 
	'Porter', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	37, 
	'Northern Brewer, Willamette, Cascade', 
	'Robust and complex, our Porter is a bittersweet tribute to the legendary freighter’s fallen crew—taken too soon when the gales of November came early.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/edmund_fitzgerald_snow.jpeg?itok=Vc9QIFCu'),
	('Hazecraft', 
	6.7, 
	'IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	40, 
	'Simcoe, Azacca, Lemondrop, Mosaic', 
	'3, 2, 1... we have haze! A cloudy cosmos of Azacca, Lemondrop, and Simcoe hops awaits exploration.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/hazecraft_teku_glass.jpeg?itok=Wdl-EllT'),
	('Crush Worthy', 
	4.0, 
	'Citrus Wheat', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	10, 
	'Mt. Hood', 
	'Do you believe in love at first sip? With a lightly filtered body and a sweet kiss of orange, its more than a crush. Its your new main squeeze.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/crushworthy_sunset.jpeg?itok=BuF0h0k0'),
	('Tropicostal', 
	6.0, 
	'Tropical IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Great Lakes'), 
	60, 
	'Idaho 7, Lemondrop, Mosaic, Calypso', 
	'Make a splash landing into paradise and discover a golden oasis of tropical fruit notes. It’s a hoppy hideaway you’ll want to escape to again and again.', 
	true, 
	'https://www.greatlakesbrewing.com/sites/default/files/styles/beer_sliders/public/tropicoastal_with_fruit.jpeg?itok=u1IwOEOC'),
	('American Lager', 
	4.5, 
	'Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	16, 
	'', 
	'Finally, a light-bodied lager that doesn’t skimp on the flavor. This clean, refreshing take on the lager style masterfully blends Saaz hops with malt sweetness to create a crisp, thirst-quenching brew that’s perfect for drinking in the hot summer sun.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_27/b357486e90a14097986193d63c1f9c3c_640x640.jpg'),
	('Doom Pedal', 
	5.49, 
	'Wheat Beer', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	20, 
	'', 
	'Brewed in memory of the late Allen White, close friend and family member of Fifty West Brewery, this Belgian-style White Ale pours a hazy blonde. Coriander, orange peel and grains of paradise come together to masterfully blend black peppery spiciness with crisp, sweet citrusy notes. Spread the love!', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_09/27551442af31ca5b894b9b64c06985f6_640x640.jpg'),
	('Coast to Coast', 
	6.8, 
	'India Pale Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	60, 
	'', 
	'Named after Route 50, which spans the US from coast to coast. This American-style IPA seeks to blend the fruity and balanced attributes of an East Coast IPA with the dank, resin characteristics of the West Coast style.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_09/4a1ffce00f0fd3c12ef6740b4f415fb7_640x640.jpg'),
	('Shortcut', 
	4.7, 
	'Hazy Pale Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_13/796bcc5bf5716dc6b91f7c492dbf21b5_640x640.jpg'),
	('Main Street', 
	5.0, 
	'Amber Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	55, 
	'', 
	'This incredibly balanced Amber Ale gets its name from Route 50, affectionately known as America’s Main Street. Think toasty malts and light, earthy hops, which blend to create this crisp, crushable beer.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_10/4ae586d8f4a45b5e2609e39edc0a9305_640x640.jpg'),
	('Pilsner', 
	4.7, 
	'German Pilsner', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'Brewed with German Pilsner malt and German Tettnang hops, this Northern German Pilsner was cold fermented for 3 weeks before being lagered for an additional 8 weeks. Expect a balanced light beer with a dry finish and frothy head.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_09/2416ba8afcd55dad03c9f9f984964c1f_640x640.jpg'),
	('Helles Lager', 
	5.5, 
	'Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'This Helles Lager was brewed with German Pilsner and Vienna malts lending a crackery backbone with light hints of honey. ', 
	true, 
	'https://untappd.akamaized.net/photo/2022_03_31/8520dac6770e94ca93298895006c386d_c_1143396755_640x640.jpg'),
	('Cider', 
	5.3, 
	'Macintosh Apple Cider', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2021_12_30/75154d79f3db76218823c974834a9474_640x640.jpg'),
	('Intersection', 
	6.8, 
	'Hazy IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	65, 
	'', 
	'Expect spicy, citrusy flavors, with an herbaceous and lemony aroma from a sorachi-ace dry hop.', 
	true, 
	'https://untappd.akamaized.net/photo/2016_04_30/3824b2a9046399478b019b0ad79b9893_320x320.jpg'),
	('Mud Tires', 
	7, 
	'Stout', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_10/7ebdf4cea4bb96ba13a8de1353ece311_640x640.jpg'),
	('Gotta Split', 
	11.5, 
	'Imperial Stout', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'Peanut Butter & Banana Imperial Stout', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_27/0a283ff51e6a96d2531689f7bd4010b3_640x640.jpg'),
	('Going Plaid', 
	8.0, 
	'Scotch Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	23, 
	'', 
	'Fermented at a cooler temperature to ensure a smoother brew, this Scotch Ale pours a dark honey color. Expect a fruity apple and pear aroma followed by a malt-forward flavor of juicy fresh plums.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_17/4feb9cd956122f49745295fcaa938cbd_640x640.jpg'),
	('Chasing Sunsets', 
	5.0, 
	'Peach Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'A deliciously juicy fruit beer brewed with peaches and just a touch of wheat malt. Approachable, peachy, and perfect for a warm spring day.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_15/6c6ec173474f25525b9aa0301821e413_640x640.jpg'),
	('Fuel Up', 
	5, 
	'Coffee Blonde Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = '50 West'), 
	0, 
	'', 
	'Our love for coffee and using local ingredients strikes again. We took the opportunity to brew with a new roaster and chose One Lines (Columbus, OH) Costa Rican coffee El Venado, which provides notes of bakers chocolate and red berries. Expect big notes of coffee, caramel, hints of stone fruit and subtle chocolate.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_07/d621e6b0a71019248c838f8999f9ee77_640x640.jpg'),
	('Vlad', 
	5.3, 
	'Pilsner', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	17, 
	'Czech-Saaz', 
	'Clean world-class pilsner brewed with czech-saaz hops.', 
	true, 
	'http://cdn.shopify.com/s/files/1/0278/6495/7016/products/VladPilsnerIG_1_1200x1200.png?v=1644238089'),
	('Reba', 
	5.3, 
	'Strawberry Blonde', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	10, 
	'', 
	'List - Effervescent - Refreshing', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_08/efaf223c8c32a35a1e8ea4728a001453_640x640.jpg'),
	('Bootsy', 
	7, 
	'Brewski IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	21, 
	'Mosaic', 
	'Dry & crisp IPA brewed with Mosaic with huge floral notes.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_15/2cf16c1a16bd736983bf5c1f8832840b_640x640.jpg'),
	('Acoustic', 
	4, 
	'Light Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	0, 
	'', 
	'Extra light and easy drinking.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_02_06/f05b35e09a2eeee2ea5b5ec915b8f730_640x640.jpg'),
	('Trey', 
	5.7, 
	'Amber Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	19, 
	'', 
	'Medium Body - Rich Amber Color - Subtle Spice', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_23/db6eb26eae1c3c2468d8d7749faa7d95_640x640.jpg'),
	('Improv', 
	7.1, 
	'West Coast IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	69, 
	'Mosaic, Citra, Idaho 7 Hops', 
	'Citrusy & Dank', 
	true, 
	'https://untappd.akamaized.net/photos/2022_02_03/c8066ed4727c3944989ee0179c4dbfa5_640x640.jpg'),
	('Island Style', 
	5, 
	'Tropical Red', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	0, 
	'', 
	'Red Ale infused with Key Lime', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_08/bc074b85605c804957d9e63f14647ece_640x640.jpg'),
	('Peso In My Hand', 
	4.9, 
	'Mexican Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Fretboard'), 
	12, 
	'', 
	'Refreshing style lager brewed with corn mash.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_02/0ca985b4c585c292e6ccffed4eda16b4_640x640.jpg'),
	('HighGiant Dank', 
	7.3, 
	'Dank IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'High Grain'), 
	0, 
	'', 
	'Dank. Intense. Brewed in collaboration with our neighbors at Nine Giant, this Dank IPA is might intense. Heavy handed with the brewers green leaf and malt, a tangy, vibrant and pungent profile awaits!', 
	true, 
	'https://untappd.akamaized.net/photos/2021_08_01/f17da8347791935c74dfb9e5d5ac2a21_640x640.jpg'),
	('Graf', 
	5.4, 
	'Mexican Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'High Grain'), 
	0, 
	'', 
	'Light. Crisp. Refreshing', 
	true, 
	'https://untappd.akamaized.net/photos/2021_07_18/554c7585007b0ab1a9e8560ea4e561bc_640x640.jpg'),
	('Myrtle', 
	4.1, 
	'Grapefruit Gose', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'High Grain'), 
	0, 
	'', 
	'Fruity. Salty. Refreshing.', 
	true, 
	'https://highgrainbrewing.square.site/uploads/1/2/5/7/125737871/s283414570639095249_p1274_i1_w3018.jpeg?width=640'),
	('Louisa', 
	4.5, 
	'Berry Sour Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'High Grain'), 
	0, 
	'', 
	'Tart. Fruity. Bright', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_11/25883fbffee429cae45c4a81d45fad6a_640x640.jpg'),
	('Lusen', 
	5.0, 
	'Pilsner', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'High Grain'), 
	0, 
	'Saaz', 
	'Medium to light crisp body, finishing with a classic herbal and spicy flavor from the noble hop, saaz.', 
	true, 
	'https://media-cdn.tripadvisor.com/media/photo-m/1280/1c/ed/8d/0e/lusen-pilsner.jpg'),
	('Rylan', 
	5, 
	'Lager - Helles', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	20, 
	'Hallertau Mittlefruh', 
	'German Style Helles: Soft bready malt with a touch of sweet floral from the classic Hallertau Mittlefruh hop. ', 
	true, 
	'https://untappd.akamaized.net/photos/2021_02_27/fe90828d5d32b56d42c84da9bbf78943_640x640.jpg'),
	('Pass the Mic: Enigma', 
	5.3, 
	'Pale Ale - American', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	50, 
	'Enigma, Idaho 7, Huell Melon', 
	'Hazy Pale hopped with Enigma, Idaho 7, & Huell Melon. Bursting with tropical passion fruit, honeydew & cantaloupe', 
	true, 
	'https://untappd.akamaized.net/photos/2021_12_25/38c787247158dc83193e844357ca611c_640x640.jpg'),
	('Retrograde', 
	7, 
	'IPA - American', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	69, 
	'Citra, Amarilla', 
	'West Coast Style IPA with Citra & Amarillo', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_09/1c3a9ab3599e11028e71412c6d79c277_640x640.jpg'),
	('Codex', 
	5.5, 
	'Farmhouse Ale - Saison', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	24, 
	'', 
	'A crisp, dry saison with aromas of fresh tangerine, honeysuckle and lilac', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_30/ceda7206cb708bfe0e996105a403ab65_640x640.jpg'),
	('Graveyard Shift', 
	10.4, 
	'Stout', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	47, 
	'', 
	'Imperial Pastry Stout w/ Cocoa Nibs, Madagascar & Tahitian Vanilla.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_02_27/c82e5ae180586bc76d57aeb9f39286d8_640x640.jpg'),
	('HigherGiant Dank', 
	8.4, 
	'IPA - Double/Imperial', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	77, 
	'Columbus, Simcoe, Centennial, Kohatu, Calypso, Zappa', 
	'Collaboration with HighGrain Brewing. West coast DIPA pushing plenty of tropical & dank flavor on a spare west coast malt frame. Featuring Columbus, Simcoe, Centennial, Kohatu, Calypso, & Zappa ', 
	true, 
	'https://untappd.akamaized.net/photos/2021_06_02/13995542dfe671ebfb4ef651faf66679_640x640.jpg'),
	('Escape Engine', 
	5, 
	'Lager - Dark', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	19, 
	'', 
	'Mexican Dark Lager - clean toasty malt and a crisp quenching finish.', 
	true, 
	'https://untappd.akamaized.net/photos/2021_11_06/d0dd510163c54cbed0521f5e88fcffc5_640x640.jpg'),
	('Light of the Past', 
	6.6, 
	'IPA - New England/Hazy', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	64, 
	'Sultana, Lotus, Sabro, Hallertau Blanc, Chinook', 
	'Notes of papaya, mango, citrus rind, candied tropical fruit, and a subtle coconut - slightly resinous finish. Its banger level tasty!', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_14/724251758eac027eacdab88a6b8067d9_640x640.jpg'),
	('Kicked It In the Sun', 
	4, 
	'Sour - Fruited Berliner Weisse', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	4, 
	'', 
	'Berliner Weisse with lemon puree, zest, milk sugar and vanilla.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_06/fc4dd1b072ae65b80db139105569ba48_640x640.jpg'),
	('Happiness Is All the Rage', 
	4.7, 
	'Sour - Berliner Weisse', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Nine Giant'), 
	4, 
	'', 
	'Guava Ginger Berliner Weisse', 
	true, 
	'https://untappd.akamaized.net/photos/2022_03_09/ff3e4311e064c84100bb547fc2660364_640x640.jpg'),	   
	('Truth', 7.2, 'IPA', 
	   (SELECT brewery_id
	   FROM breweries
	   WHERE brewery_name = 'Rhinegeist'), 75, 'Amarillo, Citra, Simcoe, Centennial', 
	   'Rare are moments of truth, when you’ve struck the last match, belting out tunes with your friends, staring deep into the campfire – times when you feel infinite. Our Truth is found in the scintillating brilliance of hops. Brewed with a nod to the Pacific, hops sizzle with tropical fruit aroma, grapefruit and mango notes and a dry finish.', true, 
	   'https://rhinegeist.com/wp-content/uploads/2019/04/Truth_2019-9-576x380.jpg'),	
	('Bubbles RGBevs', 
	5, 
	'Hard Craft Beverage', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Rhinegeist'), 
	0, 
	'', 
	'Clear light red color with little to no haze. Aromas of red apple, cranberry and peach are backed by moderate sweetness with a very mild acidity. The body is light, with moderate carbonation and lingering notes of apple and cranberry.', 
	true, 
	'https://pbs.twimg.com/media/FOozX99XEAkBQfS?format=jpg&name=4096x4096'),
	('Cheetah', 
	4.8, 
	'Lager', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Rhinegeist'), 
	6, 
	'Saphir', 
	'Swift in body and mind, Cheetah sprints ever forward. A blur of pure instinct. Buena onda. Pure, crisp, clean. Blissful simplicity. Savor this moment. All we have and all we need is now. Feel free and therefore you are free.', 
	true, 
	'https://beerconnoisseur.com/sites/default/files/styles/beer_page_245w/public/beer/cheetah-rhinegeist-brewery.jpg?itok=4YQ23bsl'),
	('Knowledge', 
	8.5, 
	'Imperial IPA', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Rhinegeist'), 
	98, 
	'Simcoe, Centennial, Chinook, Columbus', 
	'desc', 
	true, 
	'Intense & refined, Knowledge delivers notes of resinous pine, dank sap, pithy grapefruit, & ripe pineapple. Chewy hops, a zesty punch; this erudite Imperial India Pale Ale sharpens perceptive depths in the studious night.'),
	('Crumb Cake', 
	7, 
	'Imperial Red Ale', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Rhinegeist'), 
	0, 
	'', 
	'Additions of coffee, vanilla and lactose give Crumb Cake a rich and creamy profile layered with streusel-inspired flavor. Crumb Cake is a seasonal release, available November-Feburary', 
	false, 
	'https://rhinegeist.com/wp-content/uploads/2021/12/Crumb-Cake_002-4-of-6-576x576.jpg'),
	('Braxton Labs Polar Similar', 
	6.6, 
	'IPA - New England / Hazy', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	20, 
	'Mosaic, Idaho 7, Cashmere', 
	'Polar Similar is a brand new, drinkable hazy IPA. A similar malt profile as most of our IPAs, this one gets a touch of honey malt to bring a unique sweetness to the base. This beer is finished with a combination of Mosaic, Idaho 7, and Cashmere hops between the whirlpool and dry hopping additions. The result is a lovely blend of tangerine zest, citrus melon, and floral hop aromas and flavors that lend to a deliciously complex IPA.', 
	true, 
	'https://untappd.akamaized.net/photos/2022_04_03/89b22c9f10173bdfa999beda44499f74_640x640.jpg'),
	('Kentucky Home', 
	9.5, 
	'Strong Ale - American', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	14, 
	'', 
	'There’s magic in that moment. As the thoroughbreds stride from the paddock to the Post Parade the crowd rises, the familiar music begins, and together everyone sings “My Old Kentucky Home.” Yet that tradition, growing ever more beautiful by the year, isn’t the only one on that first Saturday in May. There are roses, Mint Juleps (oh, the Mint Juleps), and of course, the most exciting two minutes in sports. So let’s lift one to the traditions that make this Commonwealth uncommon. Enjoy this Kentucky Home, a smooth blend of our beer with a dash of Julep Bourbon and oak. They’re at the post…', 
	true, 
	'https://cdn.shopify.com/s/files/1/0876/7460/products/KentuckyHome_1080x1080_26a49eac-1ddd-4d47-a676-c990e32bb13f_1500x.png?v=1649260839'),
	('Mantro Toasted Coconut', 
	9.5, 
	'Stout - Imperial / Double Pastry', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	40, 
	'', 
	'Mantra is a big, bold, pastry stout. An array of specialty grains bring together a complex malt profile of caramel, milk chocolate, toffee, and a touch of coffee. Minimal hops bring just the right amount of bitterness. We brewed and fermented it to leave enough sugars behind to create a robust and creamy mouthfeel. Each release sees Mantra conditioned on a different set of adjuncts that bring to life some of your favorite dessert flavors. This variant of Mantra sees extended aging on freshly toasted coconut and delicious cacao nibs. The result sees this complex sweet stout get more intense with big tropical flavors, delicate nutty sweetness, and slightly bitter dark chocolate.', 
	true, 
	'https://scontent-ort2-1.xx.fbcdn.net/v/t39.30808-6/278486312_3044336635784672_2776288655037607984_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=730e14&_nc_ohc=9FEQrA35TFgAX9t2f3P&_nc_ht=scontent-ort2-1.xx&oh=00_AT_trb6KmE_wWDls6AH2C3avLd2QAXVcLlDkPMncjMsmcg&oe=626577A8'),
	('Birdie Citrus Grape Fusion', 
	5, 
	'Hard Setlzer', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	0, 
	'', 
	'We don’t take a single day for granted, and a little Birdie told us not to wait ’til sunset to celebrate. With light effervescence and a friendly bite, this naturally flavored fusion provides the sweet refreshment you need to keep you below par and the party in full swing. So tee up the perfect round with Birdie, an unmatched beverage that sports a burst of citrus and grape in every spirited sip. Whether you’re in the garage or out on the green, no matter the forecast or fairway, win the day with a Birdie.', 
	true, 
	'https://scontent-ort2-1.xx.fbcdn.net/v/t39.30808-6/276993559_3036002346618101_7757063408588458473_n.jpg?_nc_cat=101&ccb=1-5&_nc_sid=a26aad&_nc_ohc=-rAITrE-22EAX-L0od4&_nc_ht=scontent-ort2-1.xx&oh=00_AT8duNFy5ivHQVrU-kq2xXbc6zdikJA2Lp5MlikSIObgqw&oe=6265E3D2'),
	('Garage Beer', 
	4, 
	'Lager - American Light', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	12, 
	'Magnum', 
	'The everyones, everywhere, everyday beer. This premium lager is incredibly refreshing and thirst quenching. Brewed only with Pilsner malt and Magnum hops, brings a crisp dry finish with medium-light body and moderate carbonation. A light bitterness from the single Magnum hop addition makes this beer perfect for every occasion. Whether you are wrenching on a car, taking a hike, camping or even just having a couple cold ones in the garage with friends after a long day, Garage Beer is the perfect beer to share with life’s best moments.', 
	true, 
	'https://scontent-ort2-1.xx.fbcdn.net/v/t39.30808-6/271932719_2983155501902786_5987566355695286417_n.jpg?_nc_cat=100&ccb=1-5&_nc_sid=9267fe&_nc_ohc=Xedojrx9Pq8AX9Dtn6d&_nc_ht=scontent-ort2-1.xx&oh=00_AT9ycvk-p1im6qQm71LQeaGxLZG-hjAkuqKYdJuNQD_9lg&oe=6264B9B8'),
	('Summertrip', 
	4.2, 
	'Sour - Fruited Berliner Weisse', 
	(SELECT brewery_id FROM breweries WHERE brewery_name = 'Braxton'), 
	4, 
	'', 
	'When the weather overheated like a radiator on the fritz, it was time to step out of the garage and head somewhere cool to relax. We found every excuse to celebrate those dog days with our family and friends, because it reminded us all that summer isn’t a season, it’s a state of mind. Introducing Summertrip, a lively beer brewed to let loose and live up those days that never seem to end. This kettle soured German style ale features 50% wheat malt and is balanced with the use of lactobacillus. Very little to no hop presence allow the bready/biscuit characteristics to come through, with a nice tart Passion Fruit finish.', 
	true, 
	'https://scontent-ort2-1.xx.fbcdn.net/v/t39.30808-6/277585137_3034627876755548_4313136977206926603_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=9267fe&_nc_ohc=R6d7lwiRkWoAX-xIPkt&_nc_ht=scontent-ort2-1.xx&oh=00_AT-W6vWCG0nSw_Ln9_hJ3RsSqUE_SAxKMdbyypkzdlVCSg&oe=6264F6A6'),
	('Leaded',
6.0,
'Coffee Amber',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
25,
'',
 'coppery hue meets dark and tasty toastiness, like walking into a coffeehouse thanks to Seven Hills’ Guatemalan beans',
true,
'https://untappd.akamaized.net/photos/2022_02_26/b9f1303e5a3cc3a25f6daae1beb88d4b_640x640.jpg'),
('Sabot',
7.9,
'India Pale Ale',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
45,
'',
 'packs a punch with big-barreled hop flavor and aroma, with a clean malt base that’s still invitingly drinkable and balanced',
true,
'https://untappd.akamaized.net/photos/2021_11_05/dc8345796a4c12e9e3bd440eab848989_640x640.jpg'),

('Hollow Point',
5.8,
'Hibiscus Ale',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
4,
'',
 'crisp and tart, this flavorful ale paints the target with bright color and mixed-berry flavors uniquely crafted from a hibiscus infusion',
true,
'https://pbs.twimg.com/media/FPDEmieWUAESoxk.jpg'),

('Holster',
5.5,
'Hazelnut Cream Stout',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
21,
'',
 'our blend of toasted, roasted malt flavors with milk sugar creates a velvety soft stout that’s nutty, rich and dark',
true,
'https://scontent-ort2-1.xx.fbcdn.net/v/t39.30808-6/248283022_1033118860590752_56976396488433620_n.jpg?stp=cp0_dst-jpg_e15_p320x320_q65&_nc_cat=103&ccb=1-5&_nc_sid=8024bb&_nc_ohc=zfq2HR4g5HAAX8zhO8J&_nc_ht=scontent-ort2-1.xx&oh=00_AT9isa2rfIW1wPAmwwxWh3JEk69oWLjB01Rwh6UD2_gItg&oe=6264F9C4'),

('Fuse',
6.3,
'Tangerine Blonde Ale',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
5,
'',
 'bursting with tangerines, sweetness and acidity blend with tangy zest for a juicy fruit-forward beer that’s bright and citrusy',
true,
'https://untappd.akamaized.net/photos/2022_03_13/3d856bca7301ec2b952f269a8586dc7a_640x640.jpg'),

('Up The Hill',
6.3,
'Munich Helles',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
17,
'',
 'clean and balanced, a traditional German-style lager brewed for drinkability with a subtle hop profile and crackery pilsner malt',
true,
'https://cdn.hopculture.com/wp-content/uploads/2021/05/cartridgebrewing-up-the-hill-1000x670-1-1024x662.jpg'),

('Cartucho',
4.3,
'Mexican-Style Lager',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Cartridge'),
13,
'',
 'clean, crisp and crushable, an ultra-light cerveza blending Pilsner and Vienna malts with flaked rice in one thirst-quenching lager',
true,
'https://beeralien.com/wp-content/uploads/2021/06/cartridge_brewing_carturcho_h.jpg'),


('Voss',
4.8,
'Kolsch',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Sonder'),
0,
'',
 'A clean, crisp, and refreshing German style. Light gold in color, with a noble hop character and slight floral aroma',
true,
'https://images.squarespace-cdn.com/content/v1/58c814d2414fb5205e266a1c/1621614468074-P403SZJYL6DILRLTTYI0/Voss+Website+NP.jpg?format=750w'),

('Blanc',
5.4,
'White Ale',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Sonder'),
0,
'',
 'Crisp citrus and subtle spice',
true,
'https://images.squarespace-cdn.com/content/v1/58c814d2414fb5205e266a1c/1621614498242-GN2MGXG7USLGI1RRGN5R/Blanc+Website+NP.jpg?format=750w'),

('You Betcha!',
6.5,
'New England Style IPA',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Sonder'),
0,
'',
 '2019 Cincinnati IPA Madness Winner. A hoppy, hazy, tropical fruit explosion with a juicy and soft texture leaving bitterness behind',
true,
'https://images.squarespace-cdn.com/content/v1/58c814d2414fb5205e266a1c/1621614533981-G47NVR8XM6LOLB0WYNTO/You+Betcha+Website+NP.jpg?format=750w'),

('Record Hop IPA',
6.8,
'type',
(SELECT brewery_id FROM breweries WHERE brewery_name = 'Sonder'),
0,
'',
 'Rotating Hops IPA. A traditional West Coast IPA with a hand-selected hop blend that changes periodically. Our production teams loves to experiment with hops, and this is their avenue to do it!',
true,
'https://images.squarespace-cdn.com/content/v1/58c814d2414fb5205e266a1c/1636470512611-AVHSLEONTA1BE7VHEVYB/Record+Hop+Vol+6+Website.jpg?format=750w');


CREATE SEQUENCE seq_review_id
 INCREMENT BY 1
  NO MAXVALUE
  NO MINVALUE
  CACHE 1;
CREATE TABLE reviews(
	review_id int DEFAULT nextval('seq_review_id'::regclass) NOT NULL,
	review varchar(10000) NOT NULL,
	rating int NOT NULL CHECK (rating >= 5),
	review_date TIMESTAMP,
	beer_id int CONSTRAINT fk_beers REFERENCES beers(beer_id) NOT NULL,
	reviewer_id int CONSTRAINT fk_users REFERENCES users(user_id)
);


INSERT INTO reviews (review, rating, beer_id, reviewer_id)
VALUES ('That is one good beer!', 5, (
SELECT beer_id
FROM beers
WHERE beer_name = 'Truth'),(
SELECT user_id
FROM users
WHERE username = 'Zach'));

COMMIT TRANSACTION;
